#!/bin/bash
IP=$1
SSHURL='pi@'$IP

ssh-keygen -R $IP > /dev/null 2>&1
timeout 0.1 ssh -o StrictHostKeyChecking=no $SSHURL > /dev/null 2>&1
sshpass -p $PI_PASSWORD ssh -o StrictHostKeyChecking=no $SSHURL
